services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fulldemo_flask_exam
    depends_on:
      - mysql
      - redis
      # - mysql_comments  # Commented out
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    container_name: fulldemo_mysql_exam
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  # mysql_comments:
  #   image: mysql:latest
  #   container_name: fulldemo_mysql_comments
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${COMMENTS_DB_PASSWORD}
  #     MYSQL_DATABASE: ${COMMENTS_DB_NAME}
  #   volumes:
  #     - mysql_comments_data:/var/lib/mysql
  #   ports:
  #     - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fulldemo_phpmyadmin_exam
    depends_on:
      - mysql
      # - mysql_comments  # Commented out
    environment:
      PMA_HOST: mysql
      # PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8080:80

  arangodb:
    image: arangodb:latest
    container_name: fulldemo_arangodb_exam
    environment:
      ARANGO_ROOT_PASSWORD: password
    volumes:
      - arangodb_data:/var/lib/arangodb3
    ports:
      - 8529:8529

  redis:
    image: redis:latest
    container_name: fulldemo_redis_exam
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  # mysql_comments_data:  # Commented out
  arangodb_data:
  redis_data:
